name: Hungary fan1-146-2

on:
  schedule:
    - cron: '32 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['59/55.0', '59/55.5', '59/55.8', '59/55.9', '59/56.0', '59/56.5', '59/57.0']
    steps:
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config.json"
          json: ${{ secrets.CONFIG }}
      - name: Test python
        run: |
          BASE_URL=${{ secrets.BASE_URL }}
          python3 v_h/h.py ${{ matrix.tag }} "146" "2" "$BASE_URL"
